// projects/react-query/src/App.tsx
import { useState } from 'react';
import { PetList } from './components/PetList';
import { CreatePetForm } from './components/CreatePetForm';
import { PetDetails } from './components/PetDetails';
import { HealthStatus } from './components/HealthStatus';
import { FileUpload } from './components/FileUpload';

/**
 * Main App component demonstrating React Query v5 hooks usage
 *
 * This app showcases all the generated hooks from the petstore API:
 * - Query hooks (useListPets, useGetPet, etc.)
 * - Mutation hooks (useCreatePet, useUpdatePet, useDeletePet, etc.)
 * - Query key usage for cache invalidation
 * - Query options for prefetching
 * - FormData mutations for file uploads
 */
export default function App() {
  const [selectedPetId, setSelectedPetId] = useState<string | null>(null);
  const [showCreateForm, setShowCreateForm] = useState(false);

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '20px' }}>
      <header style={{ marginBottom: '30px' }}>
        <h1>Petstore - React Query v5 Demo</h1>
        <p>Integration test project for @schema-gen/plugin-react-query-v5</p>
      </header>

      <div style={{ marginBottom: '20px' }}>
        <HealthStatus />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
        <section>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <h2>Pets</h2>
            <button onClick={() => setShowCreateForm(!showCreateForm)}>
              {showCreateForm ? 'Cancel' : 'Add Pet'}
            </button>
          </div>

          {showCreateForm && (
            <div style={{ marginBottom: '20px', padding: '15px', border: '1px solid #ccc' }}>
              <CreatePetForm onSuccess={() => setShowCreateForm(false)} />
            </div>
          )}

          <PetList onSelectPet={setSelectedPetId} selectedPetId={selectedPetId} />
        </section>

        <section>
          <h2>Details</h2>
          {selectedPetId ? (
            <PetDetails petId={selectedPetId} onClose={() => setSelectedPetId(null)} />
          ) : (
            <p>Select a pet to view details</p>
          )}
        </section>
      </div>

      <section style={{ marginTop: '30px' }}>
        <h2>File Upload</h2>
        <FileUpload />
      </section>
    </div>
  );
}

// projects/vue-query/src/App.vue
<script setup lang="ts">
/**
 * Main App component with navigation layout
 *
 * This app showcases all the generated Vue Query composables from the petstore API:
 * - Query composables (useListPets, useGetPet, etc.)
 * - Mutation composables (useCreatePet, useUpdatePet, useDeletePet, etc.)
 * - Query key usage for cache invalidation
 * - Vue Router integration for REST-like navigation
 */
import { RouterView, RouterLink, useRoute } from 'vue-router';
import { computed } from 'vue';

const route = useRoute();

const navItems = [
  { to: '/pets', label: 'Pets', icon: '🐾' },
  { to: '/users', label: 'Users', icon: '👥' },
  { to: '/files', label: 'Files', icon: '📁' },
  { to: '/health', label: 'Health', icon: '💚' },
];

const isActive = (path: string) => computed(() => route.path.startsWith(path));
</script>

<template>
  <div class="app">
    <header class="header">
      <div class="header-content">
        <h1 class="logo">
          <RouterLink to="/">Petstore</RouterLink>
        </h1>
        <p class="subtitle">Vue Query Demo</p>
      </div>
      <nav class="nav">
        <RouterLink
          v-for="item in navItems"
          :key="item.to"
          :to="item.to"
          :class="['nav-link', { active: isActive(item.to).value }]"
        >
          <span class="nav-icon">{{ item.icon }}</span>
          {{ item.label }}
        </RouterLink>
      </nav>
    </header>

    <main class="main">
      <RouterView />
    </main>

    <footer class="footer">
      <p>Integration test project for @schema-gen/plugin-vue-query-v4</p>
    </footer>
  </div>
</template>

<style scoped>
.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.header {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 20px;
}

.header-content {
  max-width: 1200px;
  margin: 0 auto;
}

.logo {
  margin: 0;
  font-size: 1.5rem;
}

.logo a {
  color: white;
  text-decoration: none;
}

.subtitle {
  margin: 5px 0 0;
  opacity: 0.8;
  font-size: 0.9rem;
}

.nav {
  max-width: 1200px;
  margin: 20px auto 0;
  display: flex;
  gap: 10px;
}

.nav-link {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 16px;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 6px;
  color: white;
  text-decoration: none;
  transition: background 0.2s;
}

.nav-link:hover {
  background: rgba(255, 255, 255, 0.2);
  text-decoration: none;
}

.nav-link.active {
  background: rgba(255, 255, 255, 0.3);
}

.nav-icon {
  font-size: 1.1rem;
}

.main {
  flex: 1;
  max-width: 1200px;
  width: 100%;
  margin: 0 auto;
  padding: 30px 20px;
}

.footer {
  text-align: center;
  padding: 20px;
  color: #666;
  font-size: 0.85rem;
  border-top: 1px solid #eee;
}
</style>
